version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - dkvasnicka
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: eslint-config-standard
    versions:
    - 14.1.1
  - dependency-name: "@release-it/conventional-changelog"
    versions:
    - 1.1.4
