version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 65
    checks:
      Similar code:
        enabled: false
ratings:
  paths:
  - "**.**"
exclude_paths:
- "**/test/**/*_test.js"
