version: 2
jobs:
  build:
    working_directory: /tmp/quadro
    docker:
      - image: shapigor/quadro
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
      - image: mongo:3
    steps:
      - checkout
      - restore_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}
      - run: npm install && npm link .
      - run: cd examples/app && npm install && npm link quadro
      - run: npm test
      - save_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}
          paths:
            - node_modules
            - examples/app/node_modules
      - store_artifacts:
          path: /tmp/quadro/coverage/lcov-report
          destination: coverage
