version: 2
jobs:
  build:
    working_directory: /tmp/quadro
    docker:
      - image: shapigor/quadro
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
      - image: mongo:3
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}
      - run: npm install && npm link .
      - run: cd examples/app && npm link quadro
      - type: shell
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter \
          && chmod +x ./cc-test-reporter \
          && ./cc-test-reporter before-build \
          && npm test \
          && ./cc-test-reporter after-build --exit-code $?
        environment:
          TERM: dumb
          CC_TEST_REPORTER_ID: 95f6f8f8d5f0b91ef00aee31e4525e1b46c0ee5e564cfdd61437bb3679d1f167
      - save_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}
          paths:
            - node_modules
            - examples/app/node_modules
      - store_artifacts:
          path: /tmp/quadro/coverage/lcov-report
          destination: coverage
