version: 2
jobs:
  build:
    working_directory: /tmp/quadro
    environment:
      CC_TEST_REPORTER_ID: 3d18819215fd7b98812a2b5f1489a6706968b93a947ad1dbe278cffd41c99b38
    docker:
      - image: shapigor/quadro
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
      - image: mongo:3
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}-1
      - run: npm install && npm link .
      - run: cd examples/app && npm install && npm link quadro
      - type: shell
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter \
          && chmod +x ./cc-test-reporter \
          && ./cc-test-reporter before-build \
          && npm test \
          && ./cc-test-reporter after-build --exit-code $?
        environment:
          TERM: dumb
          CC_TEST_REPORTER_ID: 3d18819215fd7b98812a2b5f1489a6706968b93a947ad1dbe278cffd41c99b38
      - save_cache:
          key: quadro-{{ checksum "package.json" }}-{{ checksum "examples/app/package.json" }}-1
          paths:
            - node_modules
            - examples/app/node_modules
